social_network/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthor.as_view(), name='author'),
    path('tech/', views.AboutTech.as_view(), name='tech')
]

social_network/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.posts, name='group'),
    path('profile/<slug:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'
         ),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'
         ),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

social_network/social_network/urls.py
from api.views import CommentViewSet, GroupViewSet, PostViewSet
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken import views

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'posts/(?P<post_id>\d+)/comments', CommentViewSet)


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/v1/', include(router.urls)),
    path('api/v1/api-token-auth/', views.obtain_auth_token),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

social_network/posts/models.py
from core.models import CreateModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.TextField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'дата публикации',
        auto_now_add=True,
        null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]


class Comment(CreateModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='comments'
    )
    text = models.TextField()


class Follow(models.Model):
    follower = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

social_network/posts/forms.py
from django import forms

from .models import Comment, Post


class CreatePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CreateComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

social_network/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt

from .forms import CreateComment, CreatePost
from .models import Comment, Follow, Group, Post, User


# @cache_page(20*1, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = User.objects.get(username=username)
    posts = Post.objects.filter(author=user)
    posts_count = posts.count()
    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = (
        request.user.is_authenticated
        and request.user != user
        and Follow.objects.filter(follower=request.user, author=user).exists()
    )
    context = {
        'page_obj': page_obj,
        'posts_count': posts_count,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    user = User.objects.get(username=post.author)
    form = CreateComment(request.POST or None)
    comments = Comment.objects.filter(post=post)
    users_posts_count = Post.objects.filter(author=user).count()
    context = {
        'page_obj': post,
        'users_posts_count': users_posts_count,
        'comments': comments,
        'form': form
    }
    return render(request, template, context)


@csrf_exempt
@login_required
def post_create(request):
    template = 'posts/create_post.html'
    grouplist = Group.objects.all()
    if request.method == 'POST':
        form = CreatePost(
            request.POST or None,
            files=request.FILES or None,
        )
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user)
    else:
        form = CreatePost()
    return render(request, template, {'form': form, 'grouplist': grouplist})


@csrf_exempt
@login_required
def post_edit(request, post_id):
    template = 'posts/edit_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = CreatePost(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'GET':
        if not request.user == post.author:
            return redirect('posts:post_detail', post_id=post_id)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, template, {'form': form, 'is_edit': 'is_edit'})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CreateComment(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__follower=request.user)
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follow_check = Follow.objects.filter(author=author, follower=request.user)
    if author != request.user and not follow_check.exists():
        Follow.objects.create(follower=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(Follow,
                      follower=request.user,
                      author__username=username).delete()
    return redirect('posts:profile', username=username)

social_network/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
<title>New post</title>
{% endblock %}
{% block content %}
<main>
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-primary">
      {% if is_edit %}
        Изменить Пост
      {% else %}
        Добавить
      {% endif %}               
    </button> 
</form>
</main>
{% include 'includes/paginator.html' %}
{% endblock %}

social_network/templates/posts/edit_post.html
{% extends 'base.html' %}
{% block title %}
<title>Update post</title>
{% endblock %}
{% block content %}
<main>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">
        {% if is_edit %}
          Изменить Пост
        {% else %}
          Добавить
        {% endif %}               
      </button> 
</form>
</main>
{% endblock %}

social_network/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Follow Page</title>
{% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}
{% for post in page_obj %}
<main>
  <h5>{{ post.author }}</h5>
    {% thumbnail post.image "100x50" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
  <h6>{{ post.text }}</h6>
  <h6>{{ post.pub_date }}</h6>
</main>
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

social_network/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Group Page</title>
{% endblock %}
{% block content %}
{% for post in page_obj %}
<main>
  <h5>{{ post.author }} </h5>
    {% thumbnail post.image "100x50" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
  <h6>{{ post.text }} </h6>
</main>
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

social_network/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Main Page</title>
{% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}
{% for post in page_obj %}
<main>
  <h5>{{ post.author }}</h5>
    {% thumbnail post.image "1200x300" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}" width="1" height="150">
    {% endthumbnail %}
  <h6>{{ post.text }}</h6>
  <h6>{{ post.pub_date }}</h6>
</main>
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

social_network/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
<title>Пост {{ post.id }}</title>
{% endblock title %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ page_obj.pub_date }} 
        </li>
        <!-- если у поста есть группа -->  
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %} 
        <li class="list-group-item">
          Группа: {{ page_obj.group }}
          <a href="{% url 'posts:group' page_obj.group %}">
            все записи группы
          </a>
        </li>
        <li class="list-group-item">
          Автор: {{ page_obj.author }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ users_posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' page_obj.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ page_obj.text }}
      </p>
    </article>
  </div>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' page_obj.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
</main>
{% endblock content %}

social_network/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Профайл пользователя {{ page_obj.0.author }}</title>
{% endblock %}
{% block header %}
-
{% endblock header %}
{% block content %}
<main>
    <div class="container py-5">        
      <h1>Все посты пользователя {{ page_obj.0.author }} </h1>
      <div class="mb-5">
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' page_obj.0.author %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' page_obj.0.author %}" role="button"
            >
              Подписаться
            </a>
         {% endif %}
      </div>
      <h3>Всего постов: {{ posts_count }} </h3>   
      <article>
        <ul>
          <li>
            Автор: {{ page_obj.0.author }}
          </li>
          <li>
            Дата публикации: {{ page_obj.0.pud_date }} 
          </li>
        </ul>
        <p>
          {% for post in page_obj %}
            {% thumbnail post.image "100x50" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
          <h6> {{ post.text }} </h6> 
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </article>
      <hr>
      {% endfor %}       
      <hr>
      <!-- Остальные посты. после последнего нет черты -->
      <!-- Здесь подключён паджинатор -->  
    </div>
  </main>
{% endblock %}